[package]
name = "http-hammer"
version = "0.1.0"
edition = "2024"
default-run = "http-hammer"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ncurses = {version = "5.101.0", features = ["wide"] }
crossbeam-channel = "0.5"
arrow2 = { version = "0.17", features = ["io_parquet"] }
parquet2 = "0.17"
memmap2 = "0.9"
reqwest = { version = "0.12", features = ["json", "blocking"] }
socket2 = "0.5"
nix = "0.26"
hdrhistogram = "7"
chrono = "0.4"
ratatui = "0.26"
crossterm = "0.27"
# Optional but recommended for logging
log = "0.4"
env_logger = "0.11"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
 